### ISSUE TITLE
epubmerge is cropping my manga images (kindle 11) 

### ISSUE THREAD

**Issue by Ninjabot64-gif** [JimmXinu/EpubMerge#18]
[Well,](url) its kinda making my manga images smaller. I use hakuneko to download cbz files, then i converter them to epub, after it i add them to calibre librsry and merge them, then im editing meta data (cover, publish date, publisher and author), then i converter the whole file into azw3

merged files: https://www.mediafire.com/file/specolg0ul8yrv3/Chapter+5.2+Anthology+(346).rar/file

unmerged files: https://www.mediafire.com/file/i1d72bhh2phx0x2/before+merging.rar/file

**Comment by JimmXinu** [comment]
I don't see any difference in image size between the individual chapter epub, merged epub or merged azw3 using Calibre's viewer.

The html is identical between the individual chapter epub and merged epub--as designed.  EpubMerge doesn't change the HTML.

The azw3 output, on the other hand, is completely re-written.  That's how Calibre convert works.

epub html:
```
<img style="position:absolute;left:0;top:0;" src="../Images/kcc-0001-kcc.jpg" width="1443" height="2172"/>
```
azw3 html:
```
<img src="../images/00045.jpeg" class="calibre14"/>
```
with css:
```
.calibre14 {
    height: 2172px;
    left: 0;
    position: absolute;
    top: 0;
    width: 1443px
    }
```
While the _actual_ image size is 962x1448.

So logically, the images should display the same.  

I see the full image on my Kindle, not a cropped image; although it does not fill the screen.  I speculate that it's showing the image at it's actual resolution instead of scaling up.

Regardless, IMO, you issue comes from the Convert rather than from EpubMerge.

FYI, not everybody has rar utilities already installed.  zip is much more universal.
