### ISSUE TITLE
Feature request: Add epub to merged epub

### ISSUE THREAD

**Issue by potatoeggy** [JimmXinu/EpubMerge#8]
Is there a way to add a new epub(s) to an existing epub created from EpubMerge while appending TOC entries to the end of that existing epub?

This is useful if I want to add new stories to an anthology but don't want to unmerge everything first and copy metadata over.

**Comment by JimmXinu** [comment]
You can already merge using previously merged epubs.  If you have the 'flatten TOC' option on, the apparent difference will be minimal.

But this has been requested enough times that I will think about how EpubMerge might include an automatic unmerge step.

**Comment by potatoeggy** [comment]
For my usecase, it's not quite enough as the old anthology title appears in the TOC, and a mix of single- and multi-chapter works aren't nested as I'd like (for obvious reasons) — but it's much nicer to manually remove one TOC entry over unmerging and remerging.

Thank you!

**Comment by JimmXinu** [comment]
Glad you figured something out.

FYI, if you merge previously merged epubs enough times, you will eventually bump into depth-of-directories issues based on the way epubmerge works.  I don't think I tested more than _maybe_ a dozen deep merge-of-merges.  

Once in a while should be fine.  But if this is something you want do every day or every week, I'd keep the original source books around to merge from (maybe in a different library).  Then copy the new epub into the existing Calibre book to preserve library metadata?  I'm not sure about the exact semantics of that.

One reason I hesitate to add an 'append merge' feature to EpubMerge is that it is currently completely non-destructive.  You can't accidentally wreck anything because it never changes existing books, only makes new ones.
