### ISSUE TITLE
Is there any information on how to install this plugin

### ISSUE THREAD

**Issue by paddywwoof** [JimmXinu/EpubMerge#9]
Calibre seems to have little info on installing plugins. I tried:
a. search the available plugins for 'merge' but found nothing
b. assumed I would have to install from file
c. git cloned this repo
d. tried pointing calibre at that but it seemed to want a file
e. zipped the repo then pointed calibre at that, said I was happy to take the security risk
f. calibre pops up an error saying `EpubMerge.zip` is invalid as there's no `__init__.py` file in the top level of the zip

Maybe this repo README could have a line or two explaining what to do.

**Comment by JimmXinu** [comment]
EpubMerge is definitely available via Calibre's built-in plugin installation.  

The only reasons I can think of it wouldn't appear in the list is if:
a) You already have it installed and are looking at the 'Not installed' list, or;
b) You are using a version of Calibre that's too old for (<v3.48) EpubMerge.  It's also vaguely possible that: 
c) You are using a vendor delivered version of Calibre instead of the [official release](https://calibre-ebook.com/download) that's not correctly load plugins.

To install from file, you need the zip of the plugin--`EpubMerge.zip `.  You can get it from the [EpubMerge Mobile Read plugin thread first post](https://www.mobileread.com/forums/showthread.php?t=169744) (for historical reasons, that's where Calibre gets it when installed from Get Plugins) or from the [latest release](https://github.com/JimmXinu/EpubMerge/releases) here on GitHub.

If you really want to make it yourself from the repo, there's a `makeplugin.py` script.  You can also install the zip from command line with `calibre-customize -a EpubMerge.zip`  I would expect just zipping the dir to work, too.  

You can also look at the [Introduction to plugins](https://www.mobileread.com/forums/showthread.php?t=118680) MR thread--that's basically the official documentation for installing plugins in general.

**Comment by paddywwoof** [comment]
@JimmXinu Thanks for swift response. The introduction was just the thing I needed. I was assuming that the list of installed plugins was the list of ones available rather than pressing the `get new plugins` button (on the row below the thin black line differentiating buttons acting on the obvious list and buttons that do something else). All cleared up.
